DeepSwarm:
  aco:
    ant_count: 4
    greediness: 0.5
    pheromone:
      decay: 0.1
      evaporation: 0.1
      start: 0.1
      verbose: false
  backend:
    batch_size: 64
    epochs: 5
    loss: mean_squared_error
    patience: 5
    verbose: 0
  flat_nodes:
  - FlattenNode
  - DenseNode
  - DropoutFlatNode
  - BatchNormalizationFlatNode
  max_depth: 3
  metrics: loss
  reuse_patience: 1
  save_folder: ./exemplars/manifold_bio_test/models/deepswarm/regression/
  spatial_nodes:
  - InputNode
  - Conv2DNode
  - DropoutSpatialNode
  - BatchNormalizationNode
  - Pool2DNode
Nodes:
  BatchNormalizationFlatNode:
    attributes: {}
    transitions:
      DenseNode: 1.1
      DropoutFlatNode: 1.1
      OutputNode: 0.9
    type: BatchNormalization
  BatchNormalizationNode:
    attributes: {}
    transitions:
      Conv2DNode: 1.1
      DropoutSpatialNode: 1.0
      FlattenNode: 1.0
      Pool2DNode: 1.1
    type: BatchNormalization
  Conv2DNode:
    attributes:
      activation:
      - ReLU
      filter_count:
      - 8
      - 16
      - 32
      - 64
      kernel_size:
      - 1
      - 3
      - 5
      - 7
    transitions:
      BatchNormalizationNode: 1.2
      Conv2DNode: 0.8
      DropoutSpatialNode: 1.1
      FlattenNode: 1.0
      Pool2DNode: 1.2
    type: Conv2D
  DenseNode:
    attributes:
      activation:
      - ReLU
      - Sigmoid
      output_size:
      - 30
      - 64
      - 128
      - 256
    transitions:
      BatchNormalizationFlatNode: 1.2
      DenseNode: 0.8
      DropoutFlatNode: 1.2
      OutputNode: 1.0
    type: Dense
  DropoutFlatNode:
    attributes:
      rate:
      - 0.1
      - 0.3
    transitions:
      BatchNormalizationFlatNode: 1.0
      DenseNode: 1.0
      OutputNode: 0.9
    type: Dropout
  DropoutSpatialNode:
    attributes:
      rate:
      - 0.1
      - 0.3
    transitions:
      BatchNormalizationNode: 1.1
      Conv2DNode: 1.1
      FlattenNode: 1.0
      Pool2DNode: 1.0
    type: Dropout
  FlattenNode:
    attributes: {}
    transitions:
      BatchNormalizationFlatNode: 0.9
      DenseNode: 1.0
      OutputNode: 0.8
    type: Flatten
  InputNode:
    attributes:
      shape:
      - !!python/tuple
        - 246
        - 20
        - 1
    transitions:
      Conv2DNode: 1.0
    type: Input
  OutputNode:
    attributes:
      activation:
      - Linear
      output_size:
      - 1
      shape:
      - 1
    transitions: {}
    type: Output
  Pool2DNode:
    attributes:
      pool_size:
      - 2
      pool_type:
      - max
      - average
      stride:
      - 2
      - 3
    transitions:
      BatchNormalizationNode: 1.1
      Conv2DNode: 1.1
      FlattenNode: 1.0
    type: Pool2D
max_depth: 3
